In [2]:
import numpy as np

Нормирование вектора — это получение вектора с тем же направлением, что и исходный, но с нормой 1.

Норма вектора вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой».

Длина вектора (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

Нормирование производится делением вектора на его норму.

In [3]:
import pandas as pd

In [4]:
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [5]:
# найти вектор параметров квартиры номер 5
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16])

In [6]:
# найти вектор этажей всех квартир
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

In [7]:
# вычислить вектор нежилой площади
area = Hut_Paradise_values[:, 1]
live = Hut_Paradise_values[:, 5]
print(area - live)

[13 12 15 13 17  9 20 15 25]


In [8]:
# найти продолжительность просмотров во всех квартирах за 2 недели
demo = Hut_Paradise_values[:, 4]
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
print(demo@time)

1348


In [9]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
# составить линейную комбинацию векторов v и w с коэффициентами 2 и -3
lin_comb = 2*v + (-3)*w
print(lin_comb)

[-3 14  3  4  2]


In [10]:
# проверить будет ли эта линейная комбинация ортогональна вектору u
print(lin_comb@u)

0


In [11]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [12]:
# составить матрицу доходов семьи, каждого члена семьи расположить по столбцам
all_incomes = np.array([[100,220,140], [150,200,130], [90,80,100]])
df = pd.DataFrame(all_incomes)
Incomes = df.values
Inc = Incomes.T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [13]:
# составить матрицу расходов семьи, каждого члена семьи расположить по столбцам
all_consumptions = np.array([[50,50,60], [100,80,140], [100,20,140]])
df = pd.DataFrame(all_consumptions)
Consumptions = df.values
Cons = Consumptions.T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [14]:
# доходы семьи после вычета налога в 13%
after_taxes = Inc * 0.87
after_taxes

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [15]:
# матрица, отражающая баланс семьи за месяц (т е разницу между доходами после вычета налога и расходами)
P = after_taxes - Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [16]:
a = np.matrix('1, -1, 2, 4, 0; 8, 2, 0, 5, 3; 0, 1, 2, 1, 2')
b = np.matrix('1, 0, 1, 0; 0, 0, 2, -1; 1, 0, 1, 1; 0, 1, 1, 1, ; 1, 1, 0, -1')
c = np.dot(a, b)
print(c)
print(c[0, 1])
print(c[2, 3])

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]
4
0


In [17]:
# найти тензорное произведение векторов
a = np.matrix('1; 3')
b = np.matrix('-3, 1')
print(np.dot(a, b))

[[-3  1]
 [-9  3]]


In [18]:
a = np.matrix('2, 0; 0, 2')
b = np.matrix('1, 1; 4, 5')
print(np.dot(a, b))

[[ 2  2]
 [ 8 10]]


In [19]:
a = np.matrix('1, 1; 2, -1; 1, 2')
b = a.T
np.dot(a, b)

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [20]:
A = np.array([[5, -1, 3, 1, 2], [-2, 8, 5, -1, 1]])
x = np.array([1,2,3,4,5])
A@x.T

array([26, 30])

In [21]:
A = np.array([[1, 9, 8, 5], [3, 6, 3, 2], [3, 3, 3, 3], [0, 2, 5, 9], [4, 4, 1, 2]])
B = np.array([[1,-1, 0, 1, 1], [-2, 0, 2, -1, 1]])
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [22]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x, y, z])
A.T@A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [23]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [24]:
# посчитать вектор прибыли салона по стилистам (ниже коммисия по услугам)
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
vsego = Count_DF * Price_DF
print(vsego@com)

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64


In [25]:
A = np.array([[2, 0, 0], [0, 4, 0], [0, 0, 5]])
np.linalg.inv(A)

array([[0.5 , 0.  , 0.  ],
       [0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.2 ]])

In [26]:
A = np.array([[1, 2], [1, 1]])
B = np.array([[5, -2], [-1, 4]])
summa = np.linalg.det(A+B)
print(np.linalg.det(A), np.linalg.det(B), summa)

-1.0 17.999999999999996 29.99999999999999


In [27]:
A = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 4]])
B = np.linalg.inv(A)
print(np.linalg.det(A), np.linalg.det(B))

7.999999999999998 0.12500000000000003


In [28]:
A = np.array([[1, 0, 3, 5], [0, 4, 5, 5], [0, 0, 0, 0], [0, 0, 0, 0]])
B = np.array([[1, 0, 3, 5], [0, 4, 5, 5], [0, 0, 0, 4], [0, 0, 0, 0]])
print(np.linalg.matrix_rank(A), np.linalg.matrix_rank(B))

2 3


In [29]:
# они попарно ортогональны + линейно независимы, тк непропорциональны друг другу
a = np.array([4, 1, 0]).T
b = np.array([-1, 4, 0]).T
c = np.array([0, 0, 1]).T
print(np.dot(a, b))
print(np.dot(a, c))
print(np.dot(b, c))

0
0
0


In [30]:
A = np.array([[8, 6, 11], [7, 5, 9], [6, 10, 6]])
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [31]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
a = np.array([v1, v2, v3, v4]).T
np.linalg.matrix_rank(a)

np.int64(4)

In [32]:
a

array([[ 9,  2,  4,  3],
       [10,  0,  0, -4],
       [ 7,  5,  0,  3],
       [ 7,  1,  4, -1],
       [ 9,  4,  1, -4]])

In [33]:
b = a.T
c = np.dot(b, a)
print(c)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


In [34]:
np.linalg.det(c)

np.float64(3716647.9999999995)

In [24]:
np.linalg.inv(c)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [46]:
a = np.array([[8, -1], [-7, -1]])
b = np.array([[-7, -4, 4], [-5, 10, -8]])
print(np.dot(a, b))

[[-51 -42  40]
 [ 54  18 -20]]


In [6]:
# создадим вектор из 12 значений от 0 до 24 с шагом 2
v = np.arange(0, 24, 2)
# создадим из вектора матрицу 3 на 4
d = v.reshape(3, 4)
# обратно переделаем матрицу в "плоский" вектор 
d.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [7]:
# если нужно вывести несколько элементов
# указываем в первых [] координаты нужных строк, а во вторых[] - координаты столбцов
d[[1, 0], [2, 3]]

array([12,  6])

In [9]:
# найт скалярное произведение векторов
a = np.array([-1, 2, -7, 9])
b = np.array([2, 8, 2, -1])
print(a.T@ b.T)

-9


In [10]:
# найти матрицу Грама
a = np.array([[1, 1], [1, 2]])
print(a@a.T)

[[2 3]
 [3 5]]


In [11]:
a = np.array([[1, 2], [3, 7]])
b = np.linalg.inv(a)
b

array([[ 7., -2.],
       [-3.,  1.]])

In [12]:
a = np.array([[2, 3, 8], [10, 2, 14], [-2, -2, -6]])
np.linalg.matrix_rank(a)

np.int64(2)

In [16]:
a = np.array([[1, -3, 1, 1], [2, 1, 2, -1]])
b = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])
a@b
d = np.linalg.inv(a@b)

In [17]:
c = np.array([1, 4, 5, 0]).T
e = a@c

In [19]:
d@e

array([-0.5,  1.6])

In [5]:
# решение системы линейных уравнений
#20х + 10у = 350
#17x + 22y = 500
# представим в виде массиво
A = np.array([[20, 10], [17, 22]])
B = np.array([350, 500])
X = np.linalg.solve(A, B)
print('Решение системы уравнений:', X)


Решение системы уравнений: [10. 15.]


In [ ]:
# перевести данные столбца в числовые
temperatures = pd.to_numeric(data['The temperature of the warmest month,°C'])

# перевести данные pandas в numpy
temperatures_numpy=temperatures.to_numpy()
# получим массив ЧИСЛОВЫХ данных

# отдельно из таблицы выведем инфу по столбцу и переведем ее в numpy
Latitude = pd.to_numeric(data['Latitude']).to_numpy()

In [19]:
#task1
array = np.arange(10) ** 4
array_2 = np.arange(10) ** 3
new = array + array_2
array_sum = new.sum()
array_difference = array.sum() - array_2.sum()
game_payments2 = array[1]
subscription_last = array_2[-1]

15333 2025 13308
1


In [26]:
#task2
some_data =  [
    [3, 8, 1, 0, 1, 2],
    [9, 2, 7, 3, 0, 4],
    [2, 5, 1, 3, 1, 8],
    [5, 1, 2, 1, 1, 0]
]
#1
some_data = np.array(some_data)
lines = some_data[1:4]
#2
last_column = some_data[:, -1]
#3
array_t = some_data.transpose()
#4
array_sum = np.sum(some_data)
#5
array_avg = np.mean(some_data)

[[3 9 2 5]
 [8 2 5 1]
 [1 7 1 2]
 [0 3 3 1]
 [1 0 1 1]
 [2 4 8 0]] 70 2.9166666666666665


In [ ]:
#task3
a = np.array([[3, 2, 1], [1, 6, 2], [4, 1, 5]])
b = np.array([360,300,675])
answer = np.linalg.solve(a, b)
print(answer)